### ISSUE TITLE
Binary data

### ISSUE THREAD

**Issue by xloem** [heedy/heedy#316]
The API needs a way to insert raw binary data.

Binary data needs some way of specifying the format, such as the codec for audio/video streams.

Codec ideas:
- Raw (probably good to specify # channels and sample size somehow)
- Wavpack (lossless dense vectors, FLAC is an alternative)
- Opus (audio, best compression)
- Vorbis / FLAC / MP3 (audio, common formats)
- x264 / x265 (video, common formats)
- MKV / MP4 / AVI / OGG (common container formats, specify codec internally)
- Proprietary device binary file (muse, zeo)

**Comment by dkumor** [comment]
What do you think of something like this:
Since by default, JSONSchema does not accept binary data, ConnectorDB can define a custom schema:
```json
{
   "type": "binary"
}
```

In this case, the data inserted will not be processed at all, but be interpreted as binary. There will still be the limit of 10MB per datapoint (which can be changed in the configuration).

The way to interpret these types of data will be put into the stream's datatype field. For example, a stream with h264 video clips could have the binary schema, and the datatype: `binary.video.h264`

**Comment by xloem** [comment]
sounds good to me !
I'm a little fuzzy on what issues might arise actually extracting this raw stream data from container formats such as `mkv`, but that sounds like a solvable problem.

**Comment by dkumor** [comment]
The main issue now will be using the REST API to get the binary data. The REST API expects the data to be encodable as a json array, so by default, while the data would be inserted in binary format, it would be extracted in base64 - unless a special flag is given to the REST API when getting a *single* datapoint, in which case the raw binary is given.

**Comment by xloem** [comment]
That sounds like as good a solution as any.  An app would still function downloading base64 encoded streams; it's not quite the guts of the issue.  Alternatives might include offering a bson/smile encoded view of the api, or redirecting to a url that makes a binary request if binary datapoints are queried.  If an app cares enough to want raw binary data it may want to download more than one datapoint at once.

**Comment by xloem** [comment]
Another concept here is 'dependency' of streams on each other.  Steps may actually be deterministically calculated from a raw accelerometer stream.  A highly compressed video stream may be deterministically created from a raw video stream.  It would be nice to represent that somehow.

**Comment by dkumor** [comment]
Yes, I have thought about this too - originally the goal was to create "shadow" streams which contain data extracted from other streams. This is critical for the ML components that will be added to ConnectorDB.

This will warrant its own issue, but that is something that will wait for version 0.4, since 0.3 is building up the core data-gathering and basic datasets/visualization - and 0.4 is building up the Machine Learning and Analysis systems.

**Comment by dkumor** [comment]
ConnectorDB as it is right now requires a configuration change after create to support large binary fields. Currently, data batch size is optimized for small datapoints, meaning that batches of 250 datapoints are kept in memory, until 10 batches are gathered. With large binary data, this will take several GB of RAM.

To avoid this, it will be necessary to change batch size and chunksize in `connectordb.conf`

```
"batchsize": 10
"chunksize": 2
```

**Comment by dkumor** [comment]
Since binary data can vary widely, handling things like that will be left to plugins, which can define their own object types.
